config/routes.rb
Rails.application.routes.draw do
  root 'about_me#index'

  resources :codes, only: [:index, :show]
  resources :speakings, only: [:index, :show]
  resources :writings, only: [:index, :show]
  resources :about_me, :except => [:new, :edit, :show, :delete, :destroy]

  get '/hire-me' => "about_me#hire_me"
  get "about_me/download_resume_pdf"

  get '/googled2345548c400f224.html', :to => redirect('/googled2345548c400f224.htmll')

end

app/models/code.rb
class Code < ActiveRecord::Base
end

app/models/duty.rb
class Duty < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base

  has_many :job_duties
  has_many :duties, through: :job_duties
end

app/models/job_duty.rb
class JobDuty < ActiveRecord::Base
  belongs_to :job
  belongs_to :duty
end

app/models/speaking.rb
class Speaking < ActiveRecord::Base
end

app/models/writing.rb
class Writing < ActiveRecord::Base
end

app/controllers/about_me_controller.rb
class AboutMeController < ApplicationController

  def index
    render :index
  end

  def hire_me
    render :hire_me
  end

  def download_resume_pdf
    send_file(
        "#{Rails.root}/public/Murray_Dax_Resume_July_2018.pdf",
        filename: "dax_murray_resume.pdf",
        type: "application/pdf"
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/codes_controller.rb
class CodesController < ApplicationController

  def index
    @codes = Code.all
  end

end

app/controllers/speakings_controller.rb
class SpeakingsController < ApplicationController

  def index
    @speakings = Speaking.all
  end

end

app/controllers/writings_controller.rb
class WritingsController < ApplicationController

  def index
    @writings = Writing.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/speaking_helper.rb
module SpeakingHelper
end

app/helpers/writings_helper.rb
module WritingsHelper
end

app/views/about_me/hire_me.html.erb
<div class="blog-body hire-me">

    <div class="hire-me-header">Hi!</div>

    <div>I'm Dax. I like cats, snakes, and making the world a better place. I am currently looking for my next adventure!</div>

    <div class="hire-me-header">About me:</div>
    <ul>
      <li>Motivated: I know how to start a project and how to keep momentum going.</li>
      <li>Quick learner: I know how I learn and what I need to learn, and I actively seek that out so that I can pick up new skills and tricks quickly.</li>
      <li>Passionate: When I am passionate about something, I go all in.</li>
      <li>Knows when to step away: I know when I need to let an idea marinate, I know when to reach out for advice and when to reach out for help. I know when I need to take a break so that I can let the creativity re-fill.</li>
    </ul>

  <div class="hire-me-header">About you:</div>
  <div>
    <ul>
      <li><b>Rarely is weekend work required and rarely is working late required</b>: this means that you know how to plan a project and use time effectively. Regularly requiring employees to work late and work weekends is a sign of bad project management and an inability to do proper estimation. It's also incredibly disrespectful of your employees time and their family commitments.</li>
      <li>
        <b>Inclusive leave programs:</b> this means you have family leave policies that are inclusive of your LGBTQ workers and those without traditional families. Can adoptive parents access paternal and maternal leave? Does bereavement leave include chosen-family members? Let's talk!
      </li>
      <li>
        <b>Team bonding that does not focus on alcohol:</b> this means that your 'team bonding' activities happen in places that aren't bars and where the main draw is not the beer list. Companies I've been at where this was successful have done trips to view the eclipse, opening day screenings of the latest Star Wars, ice skating at the local park, and tours of new exhibits at museums.
      </li>
      <li> <b>Mostly or 100% remote:</b> I work best when I am able to work at home. I am a slack call pro and can easily navigate a long conference call. You should have a good flow for making sure remote employees are not left out of important conversations and have systems set up to support remote work already.</li>
      <li> <b>No "Unlimited Paid Time Off"</b> UPTO structures are usually selectively enforced and subject to a lot of unconcious bias. There is often no standard for what is "too much," and so it is usually the URMs who are told they are taking too much when their coworkers take even more. UPTO often disproportionately affects people with chronic illnesses, who use that time for doctors appointments, but are then told they've taken "too much" when they ask for actual vacation time. My ideal place would have 4 weeks of vacation and 2 weeks of sick time, plus leave for family emergencies and funerals.
      </li>
      <li><b>Don't work with the military:</b> You don't have any contracts with the DOD, State Department, or other arms of the United States military or ICE.</li>
    </ul>

    <div class="hire-me-header">
      Bonus / Nice To Have</div>
    <div>
      <ul>
        <li>Working in the civic / for-good sector</li>
        <li>50% of staff at every level is not white men</li>
        <li>A generous company match on employee charitable giving</li>
      </ul>
    </div>

  </div>

  <div class="hire-me-header">Interested? <%= link_to "Download my resume!", about_me_download_resume_pdf_url %></div>


</div>

app/views/codes/index.html.erb
<div class="blog-body">
  <% @codes.each do |code| %>

      <div class="job">
        <div class="job--head">
          <div class="job--company"><%= code.project_name %></div>
        </div>
        <div class="job--description">
          <ul>
            <li class="job--item"><%= code.description %></li>
            <li class="job--item"><%= code.cool_point1 %></li>
            <li class="job--item"><%= code.cool_point2 %></li>
            <% if code.url? %><li class="job--item"><%= link_to "Preview", code.url %></li><% end %>
            <% if code.github_url? %><li class="job--item"><%= link_to "See the code", code.github_url %></li><% end %>
          </ul>
        </div>
      </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="copyright">
  <p>© Dax Murray  2012-2017. </p>
    <!--<p>Unauthorized use and/or duplication of this material without express and written permission from this sites’s author and/or owner is strictly prohibited.</p>-->
    <!--<p>Excerpts and links may be used, provided that full and clear credit is given to Dax Murray with appropriate and specific direction to the original content.</p>-->
  </div>
</footer>

app/views/layouts/_mobile_links.html.erb
<div class="mobile_links">
  <div class="mobile_img"> <%= image_tag "profile.jpg", alt: "Profile Image " %>
<div class="article--text"><a href="http://www.twitter.com/daxaeterna" target="_blank"><i class="fa fa-twitter">  </i>
</a> <a href="http://www.github.com/jdax" target="_blank"><i class="fa fa-github"></i>
  </a><a href="http://www.linkedin.com/in/daxmurray" target="_blank"> <i class="fa fa-linkedin"></i>
</a></div></div>
</div>

app/views/layouts/_mobile_nav.html.erb
<div class="mobile-nav">
<nav id="primary_nav">
<ul>
  <ul>
    <li><%= link_to "Code", codes_path%></li>
    <li><%= link_to "Speaking", speakings_path%></li>
    <li><%= link_to "Writing", writings_path %></li>
    <li><%= link_to "Curriculum Vitae", about_me_index_path %></li>
  </ul>
</ul>
</nav>
</div>

app/views/layouts/_navbar.html.erb
<div class="left-nav">

  <div class="header-image">
    <%= image_tag "profile.jpg", alt: "Profile Image ", class: "profile-pic" %>
  </div>
  <div class="header-text">
    <h1>Dax Murray</h1> <p>Software engineer: writing about, speaking about, and ranting about code.</p>
    <div class="article--text">
      <div class="social-share">
      <a href="http://www.twitter.com/daxaeterna" target="_blank"><i class="fa fa-twitter">  </i></a>
      <a href="http://www.github.com/jdax" target="_blank"><i class="fa fa-github"></i></a>
      <a href="http://www.linkedin.com/in/daxmurray" target="_blank"> <i class="fa fa-linkedin"></i></a>
    </div>
    </div>
  </div>


  <div class="left-nav-links">
    <ul>
      <li><%= link_to "Code", codes_path%></li>
      <li><%= link_to "Speaking", speakings_path%></li>
      <li><%= link_to "Writing", writings_path %></li>
      <li><%= link_to "Curriculum Vitae", about_me_index_path %></li>
      <li><a href="http://www.daxmurray.com">My Author Website</a></li>
      <li><a href="http://www.dax.cat">My Cats</a></li>
    </ul>
  </div>


  <%= render "layouts/footer" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>dax codes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=PT+Serif:700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,300italic' rel='stylesheet' type='text/css'>
  <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type =>  'image/ico' %>


  <meta charset="utf-8">
  <meta http-equiv='X-UA-Compatible' content='IE=edge;chrome=1' />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta content="Dax Murray Codes" name="Dax Murray Codes">
  <meta name="description" content="Dax Murray's coding portfolio" />

  <!-- Facebook -->
  <meta property="og:title" content="Dax Murray Codes" />
  <meta property="og:description" content="Dax Murray Codes" />
  <meta property="og:url" content="http://www.dax.codes/" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="Dax Murray Codes" />

  <!-- TWITTER -->
  <meta name="twitter:card" content="summary_large_image" >
  <meta name="twitter:site" content="@DaxAeterna">
  <meta name="twitter:site:id" content="">
  <meta name="twitter:creator" content="@DaxAeterna">
  <meta name="twitter:title" content="Dax Murray Codes">
  <meta name="twitter:description" content="Dax Murray Codes">
  <meta name="twitter:image" content="">  <%= csrf_meta_tags %>
</head>
<body>
<div id="main" role="main">
  <%= render "layouts/navbar" %>
  <div class="mobile-nav">
    <%= render "layouts/mobile_nav" %>
  </div>
  <%= render "layouts/mobile_links" %>

  <div>
    <%= yield %>
  </div>


</div>


</body>
</html>

app/views/speakings/index.html.erb
<div class="blog-body">
  <% @speakings.each do |speaking| %>

      <div class="job">
        <div class="job--head">
          <div class="job--company"><%= speaking.talk_name %></div>
        </div>
        <div class="job--description">
          <ul>
            <li class="job--item"><%= speaking.conference %></li>
            <% if speaking.conference_url? %><li class="job--item"><%= link_to "Conference Website", speaking.conference_url %></li><% end %>
            <% if speaking.slides_url? %><li class="job--item"><%= link_to "See the slides", speaking.slides_url %></li><% end %>
            <% if speaking.video_url? %><li class="job--item"><%= link_to "See the video", speaking.video_url %></li><% end %>
          </ul>
        </div>
      </div>
  <% end %>
</div>

app/views/writings/index.html.erb
<div class="blog-body">
  <% @writings.each do |writing| %>

      <div class="job">
        <div class="job--head">
          <div class="job--company"><%= writing.article_title %></div>
        </div>
        <div class="job--description">
          <ul>
            <li class="job--item"><%= writing.publication %></li>
            <li class="job--item"><%= writing.description %></li>
            <% if writing.article_url? %><li class="job--item"><%= link_to "Read it", writing.article_url %></li><% end %>
          </ul>
        </div>
      </div>
  <% end %>
</div>